### ISSUE TITLE
侧边栏的社交按钮是如何实现的？

### ISSUE THREAD

**Issue by guoguodedie** [theme-nexmoe/typecho-theme-nexmoe#2]
非常喜欢您的主题，非常漂亮！！谢谢您
但左侧的社交按钮那一列，不知道是如何实现的，能够解答一下。谢谢

**Comment by nexmoe** [comment]
仅hexo版本有，待贡献者pr

**Comment by AHCorn** [comment]
我刚刚pr了该功能~折影大佬审核通过后就可以直接下载使用啦
所有的按钮链接设置你都可以在后台的外观设置中找到的~

**Comment by AHCorn** [comment]
我刚刚pr了该功能折影大佬审核通过后就可以直接下载使用啦
所有的按钮链接设置你都可以在后台的外观设置中找到的

**Comment by AHCorn** [comment]
我刚刚pr了该功能hhh折影大佬审核通过后就可以直接下载使用啦
所有的按钮链接设置你都可以在后台的外观设置中找到的
