### ISSUE TITLE
评论框显示有问题

### ISSUE THREAD

**Issue by mou349477** [theme-nexmoe/typecho-theme-nexmoe#3]
文章下面的评论框手机显示有点问题，麻烦修复一下

**Comment by mou349477** [comment]
浏览器问题

**Comment by mou349477** [comment]
只要登录后台，评论框显示不全，麻烦修复一下

**Comment by AHQAQ** [comment]
没有发现该Bug，我猜测是以下三种情况
1.认为失效的表情功能是显示不全（目前已删除
2.邮件，名字输入是未登录状态下才会显示的
3.原本用于区分表情按钮和评论框的样式现在没用了，导致右边评论框缺了一块，现在也已经修复了
